article/urls.py
from django.contrib import admin
from django.urls import path
from . import views # article uygulamasının views modülünden views fonksiyonlarını içe aktarır.
app_name = 'article' # Uygulama adını belirtir, böylece URL'ler uygulama içinde tanımlanabilir.

urlpatterns = [
    path('dashboard/', views.dashboard, name="dashboard"), # Dashboard sayfası için URL, views.dashboard fonksiyonunu çağırır.
    path('addarticle/', views.addarticle, name="addarticle"),
    path('article/<int:id>', views.detail, name="detail"),
    path('update/<int:id>', views.update, name="update"),
    path('delete/<int:id>', views.delete, name="delete"),  # Makale silme işlemi için URL, views.delete fonksiyonunu çağırır.
    path('', views.articles, name="articles"),  # Ana sayfa için URL, views.articles fonksiyonunu çağırır. 
    path('comment/<int:id>', views.addComment, name="comment"),  # Yorum ekleme işlemi için URL, views.comment fonksiyonunu çağırır.
]    

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from article import views

app_name = 'blog'  # Uygulama adını belirtir, böylece URL'ler uygulama içinde tanımlanabilir.

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name= "index"),  # Admin paneline yönlendirme, böylece ana sayfada admin paneli açılacak.
    #name=index yazma sebebim, url'yi daha sonra kullanabilmek için. Böylece url'yi değiştirdiğimizde, kodlarımızı değiştirmemize gerek kalmaz.
    path('about/', views.about, name= "about"),
    #path('detail/<int:id>/', views.detail, name="detail"),  # Detay sayfası için dinamik URL, id parametresi ile makale detayını gösterir.
    # <int:id> kısmı, URL'de gelen id parametresini integer olarak alır ve views.detail fonksiyonuna gönderir.
    # views.detail fonksiyonunda bu id parametresini kullanarak makale detayını alabiliriz.
    path('articles/', include('article.urls')),  # article uygulamasının URL'lerini dahil eder, böylece article.urls içindeki URL'ler kullanılabilir.
    path('user/', include('user.urls')),  # user uygulamasının URL'lerini dahil eder, böylece user.urls içindeki URL'ler kullanılabilir.
   
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # Media dosyalarını statik olarak sunar, böylece kullanıcılar yüklenen medya dosyalarına erişebilir.

article/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class Article(models.Model): 
    author = models.ForeignKey("auth.User", on_delete = models.CASCADE, verbose_name="Yazar") #user tablosunu işaret ediyor, sondaki on_delete parametresi ile silindiğinde ne olacağını belirliyoruz yani kullanıcı silinince makalede silinsin dedik casdacade ile.
    title = models.CharField(max_length=50, verbose_name="Başlık") #makale başlığı, charfield ile karakter sınırlaması koyduk.
    content = RichTextField() #makale içeriği, textfield ile sınırsız karakter yazılabilir.
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma Tarihi ") #makale oluşturulma tarihi, otomatik olarak eklenir. auto_now_add ile makale ilk oluşturulduğunda tarih eklenir.
    article_image = models.FileField(blank = True, null = True, verbose_name="Makale Resmi") #makale resmi, filefield ile dosya yüklenebilir. blank ve null ile boş bırakılabilir.
    def __str__(self):
        return self.title  # Makalenin başlığını döndürür, böylece admin panelinde makale başlığı görünecektir.
    #return self.author yazsaydık da yazar bilgisi dönerdi ve articleobject yerine bu yazardı 
    
    class Meta:  # Meta sınıfı, modelin meta verilerini tanımlar.
        ordering = ['-created_date'] #başına eksi eklersek en son yazılan yorum ilk gösterilir

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name="Makale", related_name="comments") #makale ile ilişkilendirildi, makale silinirse yorum da silinir. 
    comment_author = models.CharField(max_length=50, verbose_name="İsim") #yorum yapan kişinin adı
    comment_content = models.CharField(max_length=200, verbose_name="Yorum") #yorum içeriği
    comment_date = models.DateTimeField(auto_now_add=True, verbose_name="Yorum Tarihi") #y
    def __str__(self):
        return self.comment_content  # Yorum içeriğini döndürür, böylece admin panelinde yorum içeriği görünecektir.
    
    class Meta:  # Meta sınıfı, modelin meta verilerini tanımlar.
        ordering = ['-comment_date']

article/forms.py
from django.forms import ModelForm
from .models import Article

# Create the form class.
class ArticleForm(ModelForm): #modelde oluşturduğumuz formları kullandık
    class Meta:
         model = Article # Article modelini kullanır. bağlantılı hale getirir
         # Formda hangi alanların yer alacağını belirtir.
         fields = ["title", "content", "article_image"] #author zaten direkt kullanıcı adı yazılacak diye eklemedik ve date de oto eklenecek diye eklemedik

article/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404, reverse  # render fonksiyonunu kullanarak HTML dosyalarını render eder.
from .forms import ArticleForm #şuanki forms.py dosyasından ArticleForm sınıfını içe aktarır.
from django.contrib import messages # mesajları kullanmak için içe aktarır. (opsiyonel)
from .models import Article, Comment  # Article modelini içe aktarır. Bu model, veritabanındaki makaleleri temsil eder.
from django.contrib.auth.decorators import login_required # login_required decoratorunu içe aktarır.

def index(request):
    #return HttpResponse("Merhaba Django")  # Bu fonksiyon, ana sayfada "Merhaba Django" mesajını gösterir.
    # Eğer bir template kullanmak istersek, render fonksiyonunu kullanabiliriz:
    return render(request, 'index.html')  # index.html dosyasını templates klasöründe arar. ve ordakini

def about(request):
    #return HttpResponse("Hakkımızda")  # Bu fonksiyon, hakkımızda sayfasında "Hakkımızda" mesajını gösterir.
    return render(request, 'about.html')  # about.html dosyasını templates klasöründe arar. ve ordakini 

def articles(request):
    keyword = request.GET.get("keyword")  # GET isteği ile gelen "keyword" parametresini alır. Eğer yoksa None döner.
    if keyword: # Eğer keyword parametresi varsa eğer arama yapıldıysa 
        articles = Article.objects.filter(title__contains=keyword)  # Veritabanında title alanında keyworda yazılı olan makaleleri alır.
        return render(request, "articles.html", {"articles": articles})  # articles.html dosyasını templates klasöründe arar ve ordakini gösterir. 
    articles = Article.objects.all()  # Veritabanındaki tüm makaleleri alır.
    
    return render(request, 'articles.html', {"articles":articles})  # articles.html dosyasını templates klasöründe arar ve ordakini gösterir.
    

@login_required(login_url="user:login")  # Bu decorator, bu fonksiyonun sadece oturum açmış kullanıcılar tarafından erişilebilmesini sağlar.
def dashboard(request):
    articles = Article.objects.filter(author=request.user)  # Oturum açmış kullanıcının makalelerini alır.
    context = {
        "articles": articles  # context sözlüğüne makaleleri ekler.
    }
    return render(request, 'dashboard.html', context)  # dashboard.html dosyasını templates klasöründe arar ve ordakini gösterir.

@login_required(login_url="user:login")  # Bu decorator, bu fonksiyonun sadece oturum açmış kullanıcılar tarafından erişilebilmesini sağlar.
def addarticle(request):
    form = ArticleForm(request.POST or None, request.FILES or None)  # ArticleForm sınıfından form nesnesi oluşturur. Eğer POST isteği varsa, form verilerini alır.
    if form.is_valid():  # Formun geçerli olup olmadığını kontrol eder.
        #form.save()  # Form verilerini kaydeder. Oto kaydetme
        #form.save article objesini oluşturuyor sonra save yapıyor ama biz article yaptıktan sonra saveden önce bir auother bilgisi vermek zorundayız
        article = form.save(commit=False)  # Form verilerini kaydetmeden önce Article nesnesi oluşturur. Kaydetmeyi biz yapacağız Böylece sıkıntı yaşamayız
        article.author = request.user  # Article nesnesinin author alanını, oturum açmış kullanıcıya atar.
        article.save()  # Article nesnesini kaydeder. 
        messages.success(request, "Makale Başarıyla Eklendi")  # Başarılı bir şekilde makale eklendiğinde mesaj gösterir.
        return redirect("article:dashboard")  # Article uygulamasının dashboard sayfasına yönlendirir. app_name ile tanımladığımız için article:dashboard şeklinde yazıyoruz.
    

    return render(request, 'addarticle.html', {"form":form})  # addarticle.html dosyasını templates klasöründe arar ve ordakini gösterir.

def detail(request, id): #dinamik url parametresi
    #article = Article.objects.filter(id=id).first()  # Veritabanından id'si verilen makaleyi alır. first ekledik gördüğü ilk articlı göstersin diye
    article = get_object_or_404(Article, id=id)  # Veritabanından id'si verilen makaleyi alır. Eğer makale bulunamazsa 404 sayfası gösterir. Model ve sorgu giricek parantez içine
    comments = article.comments.all()  # İlgili makalenin yorumlarını alır. modeldeki related_name ile ilişkilendirilmiş yorumları alır.

    return render(request, 'detail.html', {"article":article, "comments":comments})  # detail.html dosyasını templates klasöründe arar ve ordakini gösterir.

@login_required(login_url="user:login")  # Bu decorator, bu fonksiyonun sadece oturum açmış kullanıcılar tarafından erişilebilmesini sağlar.
def update(request, id):
    article = get_object_or_404(Article, id=id)  # Veritabanından id'si verilen makaleyi alır. Eğer makale bulunamazsa 404 sayfası gösterir.
    form = ArticleForm(request.POST or None, request.FILES or None, instance=article)  # ArticleForm sınıfından form nesnesi oluşturur. Eğer POST isteği varsa, form verilerini alır. instance ile tüm bilgiler form'a göndeririz.
    if form.is_valid():  # Formun geçerli olup olmadığını kontrol eder.
        article = form.save(commit=False) # Form verilerini kaydetmeden önce Article nesnesi oluşturur. Kaydetmeyi biz yapacağız Böylece sıkıntı yaşamayız
        article.author = request.user # Article nesnesinin author alanını, oturum açmış kullanıcıya atar.
        article.save()

        messages.success(request, "Makale Başarıyla Güncellendi")  # Başarılı bir şekilde makale eklendiğinde mesaj gösterir.
        return redirect("index")
    
    return render(request, 'update.html', {"form":form})  # update.html dosyasını templates klasöründe arar ve ordakini gösterir.

@login_required(login_url="user:login") 
def delete(request, id):
    article = get_object_or_404(Article, id=id)  # Veritabanından id'si verilen makaleyi alır. Eğer makale bulunamazsa 404 sayfası gösterir.

    article.delete()  # Article nesnesini siler.
    messages.success(request, "Makale Başarıyla Silindi")  # Başarılı bir şekilde makale silindiğinde mesaj gösterir.
    return redirect("article:dashboard")  # Article uygulamasının dashboard sayfasına yönlendirir. app_name ile tanımladığımız için article:dashboard şeklinde yazıyoruz.


def addComment(request, id):
    #ilk önce post almamız gerek
    article = get_object_or_404(Article, id=id)  # Veritabanından id'si verilen makaleyi alır. Eğer makale bulunamazsa 404 sayfası gösterir.
    if request.method == "POST":  # Eğer istek POST ise
        comment_author = request.POST.get("comment_author")  # POST isteğinden "comment_author" parametresini alır.
        comment_content = request.POST.get("comment_content")  # POST isteğinden "comment_content" parametresini alır.
        
        #bir makaleye ait yeni bir yorum (Comment) nesnesi oluşturmak ve veritabanına kaydetmektir.
        newComment = Comment(comment_author=comment_author, comment_content=comment_content)  # Yeni bir Comment nesnesi oluşturur.
        newComment.article = article  # Yeni Comment nesnesinin article alanını, alınan makaleye atar.
        newComment.save()  # Yeni Comment nesnesini kaydeder.

    # return redirect("/articles/article" + str(id)) # Yorum eklendikten sonra, makalenin detay sayfasına yönlendirir. URL'yi dinamik olarak oluşturur.
    return redirect(reverse("article:detail", kwargs={"id": id}))  # Yorum eklendikten sonra, makalenin detay sayfasına yönlendirir. reverse ile URL'yi dinamik olarak oluşturur. articles/detail/15

templates/about.html
{% extends "layout.html" %}

{% block body %}


<h3>Hakkımızda</h3>
<hr>

<p>
Herkese merhaba. Ben Melike Akıl. Şuan da Subü Bilgisayar Programcılığı öğrencisi ikinci sınıfım. Ve kendimi geliştirmek adına Python öğreniyorum. Bu siteyi de flask ve django kullanarak yaptım. 
</p>
    
{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-6 offset-md-3">
      <h3>Makale Oluştur</h3>
      <hr>
      <form method="post" enctype="multipart/form-data"> <!-- enctype="multipart/form-data" dosya yükleme için gerekli, form verilerini POST yöntemi ile gönderir. -->
    {% csrf_token %}
    {{form.media}} <!-- CKEditor için gerekli medya dosyalarını ekler -->
    <!--{{forms.as_p}} bunun yerine aşağıdakini yazıyoruz crispy kullanmak için-->
    {{ form|crispy }}  <!-- Django crispy forms ile formu daha güzel bir şekilde gösterir -->
    <br>
    <button type="submit" class="btn btn-danger">Oluştur</button>
      </form>
  </div>
</div>



{% endblock body %}

templates/articles.html
{% extends "layout.html" %}
{% load custom_filters %}
{% block body %}
<div class= "row">
    <div class="col-md-10 offset-md-3">
       <div class= "col-lg-8">
           <h3>Makaleler</h3>
           <hr>
        </div>
</div>

<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <form>
        {% csrf_token %}
        <input type="text" class="form-control me-2" name="keyword" placeholder="Ara...">
        <button type="submit" class="btn btn-danger">Ara</button>
      </form>
    </div>
  </div>
</div>
    

{% if articles %}
    {% for article in articles %}
        <div class="container mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <article>
                <header class="mb-4">
                    <a href="{% url 'article:detail' article.id %}" class="text-decoration-none">
                        <h2 class="fw-bolder mb-1">{{article.title}}</h2>
                    </a>
                    <p class="lead">by {{article.author.username}}</p>
                    <div class="text-muted fst-italic mb-2">{{article.created_date}}</div>
                </header>
                
                {% if article.article_image %}
                <a href="{% url 'article:detail' article.id %}">
                    <figure class="mb-4">
                        <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="{{article.title}}" />
                    </figure>
                </a>
                {% endif %}
                
                <p class="lead">
                    {{article.content|clean_for_preview|truncatewords:30|safe}}
                </p>
                <a style = "float : right" href="{% url 'article:detail' article.id %}" class="btn btn-primary">Devamını Oku</a>
                <hr>
            </article>
        </div>
    </div>
</div>
    {% endfor %}

{% else %}
   <div class="container mt-5">
        <div class="row justify-content-center">
           <div class="col-md-6">
                <div class="alert alert-danger">Aradığınız kriterlere uygun makale bulunamadı.</div>
            </div>
         </div>
    </div>
{% endif %}

{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}
<h3>Kontrol Paneli</h3>
<hr>

<p>
   Hoşgeldiniz. <small>{{request.user.username}}</small>
</p>
<hr>
<a class= "btn btn-danger" href="/articles/addarticle">Makale Ekle</a>
<hr>
{% if articles %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Başlık</th>
      <th scope="col">Yazar</th>
      <th scope="col">Tarih</th>
      <th scope="col">Güncelle</th>
      <th scope="col">Sil</th>
    </tr>
  </thead>
  <tbody>
    {% for article in articles %}
    <tr>
      <th scope="row">{{article.id}}</th>
      <td><a href="/articles/article/{{article.id}}">{{article.title}}</a></td>
      <td>{{article.author.username}}</td>
      <td>{{article.created_date}}</td>
      <td><a class="btn btn-primary" href="/articles/update/{{article.id}}">Güncelle</a></td>
      <td><a class="btn btn-danger" href="/articles/delete/{{article.id}}">Sil</a></td>
    </tr>
    {% endfor %}
    
  </tbody>
</table> 
{% else %} 
<div class="alert alert-warning" role="alert">
  Henüz makale eklemediniz. </div>  
{% endif %}


{% endblock body %}

templates/detail.html
{% extends "layout.html" %}

{% block body %}

<div class="container mt-5">
            <div class="row">
                <div class="col-lg-8">
                    <!-- Post content-->
                    <article>
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <h1 class="fw-bolder mb-1">{{article.title}}</h1>
                            <p class="lead">by {{article.author.username}}</p>
                            <!-- Post meta content-->
                            <div class="text-muted fst-italic mb-2">{{article.created_date}}</div>
                        </header>
                        <!-- Preview image figure-->
                        {% if article.article_image %}
                        <figure class="mb-4"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt="..." /></figure>
                        {% endif %}
                        <!-- Post content-->
                        <p class="lead"> <!--lead dikkat çekici paragraf vurgusu-->
                           {{article.content|safe}} <!-- article içeriğini güvenli bir şekilde gösterir, böylece HTML etiketleri işlenir. -->
                        </p>
                    </article>
                    
                </div>
            </div>
        </div>
        <hr>

        <h4>YORUMLAR</h4>
        <hr>
        {% if comments %}
        {% for comment in comments %}
           <div class= "media mb-4">
               <img class="d-flex mr-3 rounded-circle" src="https://via.placeholder.com/50" alt="">
                <div class="media-body">
                    <h5 class="mt-0">{{comment.comment_author}}</h5>
                    {{comment.comment_date}} <br>
                    {{comment.comment_content}}
                </div>
            </div>
        {% endfor %} 

        {% else %}
        <div class="alert alert-danger">
            Bu makaleye henüz yorum yapılmamış. İlk yorumu yapan siz olun.
        {% endif %}

        <section class="card my-4">
            <h5 class= "card-header">Yorum Ekle:</h5>
                <div class="card-body">       
                    <form method="post" action = "{% url 'article:comment' article.id %}"> 
                    {% csrf_token %}
                        <div class="form-group">
                            <label for="formGroupExampleInput">İsim</label>
                            <input name="comment_author" type="text" class="form-control" id="formGroupExampleInput" placeholder="İsminizi Giriniz">
                        <div class= "form-group">
                            <label for="formGroupExampleInput">Yorum</label>
                            <textarea name="comment_content" class="form-control" rows="3" placeholder="Yorum Yap!"></textarea></form>
                        </div>
                        <button type="submit" class="btn btn-danger">Yorumu Ekle</button>
                    </form>             
                </div>      
        </section>

{% endblock body %}

templates/index.html
{% extends "layout.html" %}

{% block body %}

<div class="jumbotron text-center">
    <h3>Yazılım Bilimi Bloguna Hoş Geldiniz!</h3>
    <p>Bu blog, yazılım bilimi ile ilgili makaleler ve içerikler sunmaktadır.</p>
</div>
 
 <p>
   {% if request.user.is_authenticated %}
       Giriş Yapıldı. {{request.user.username}} olarak giriş yaptınız.
    
    {% else %}
       
    {% endif %} 
 </p>

{% endblock body %}

templates/layout.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    
    <title>YB Blog</title>

</head>
<body>
        {% include "includes/navbar.html" %}  <!-- Navbar'ı include ile ekliyoruz. -->

       

        <div style="margin-top:100px; margin-bottom:100px;" class="container"> 
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} 
            class="{{ message.tags }}"
            {% endif %}>{{ message }}</li>
        {% endfor %}
        </ul>
        {% endif %}
        
        {% block body %}

        {% endblock body %}




          <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
          <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
          <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
          <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
          <!--poppermin eklemek için static değil de cdn yaptık-->
</body>
</html>

templates/login.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-6 offset-md-3">
      <h3>Giriş Yap</h3>
      <hr>
      <form method="post">
    {% csrf_token %}
    <!--{{forms.as_p}} bunun yerine aşağıdakini yazıyoruz crispy kullanmak için-->
    {{ form|crispy }}  <!-- Django crispy forms ile formu daha güzel bir şekilde gösterir -->
    <br>
    <button type="submit" class="btn btn-danger">Giriş Yap</button>
      </form>
  </div>
</div>



{% endblock body%}

templates/register.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-6 offset-md-3">
      <h3>Kayıt Ol</h3>
      <hr>
      <form method="post">
    {% csrf_token %}
    <!--{{forms.as_p}} bunun yerine aşağıdakini yazıyoruz crispy kullanmak için-->
    {{ form|crispy }}  <!-- Django crispy forms ile formu daha güzel bir şekilde gösterir -->
    <br>
    <button type="submit" class="btn btn-danger">Kayıt Ol</button>
      </form>
  </div>
</div>


{% endblock body%}

templates/update.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-6 offset-md-3">
      <h3>Makale Güncelle</h3>
      <hr>
      <form method="post" enctype="multipart/form-data"> <!-- enctype="multipart/form-data" dosya yükleme için gerekli, form verilerini POST yöntemi ile gönderir. -->
    {% csrf_token %}
    {{form.media}} <!-- CKEditor için gerekli medya dosyalarını ekler -->
    <!--{{forms.as_p}} bunun yerine aşağıdakini yazıyoruz crispy kullanmak için-->
    {{ form|crispy }}  <!-- Django crispy forms ile formu daha güzel bir şekilde gösterir -->
    <br>
    <button type="submit" class="btn btn-danger">Güncelle</button>
      </form>
  </div>
</div>



{% endblock body %}